name: Deploy with OpenTofu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install OpenTofu
      - name: Setup OpenTofu
        run: |
          curl -L https://github.com/opentofu/opentofu/releases/download/v0.1.0/opentofu-linux-amd64 -o opentofu
          chmod +x opentofu
          sudo mv opentofu /usr/local/bin/tofu

      # Run `tofu init`
      - name: OpenTofu Init
        run: tofu init

      # Run `tofu validate`
      - name: OpenTofu Validate
        run: tofu validate

      # Run `tofu plan`
      - name: OpenTofu Plan
        run: tofu plan -out=tfplan

      # Run `tofu apply`
      - name: OpenTofu Apply
        run: tofu apply -input=false tfplan

    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      SSH_FINGERPRINT: ${{ secrets.SSH_FINGERPRINT }}
